version: '3.8'

services:

  api:
    build:
      context: .
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - "5004:5000"
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/petapi_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/petapi_test
    depends_on:
      - api-db
  
  api-db:
    image: postgres:14.1-alpine
    volumes:
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

